# Generated by Django 5.2.7 on 2025-11-09 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=100)),
                ('matches', models.IntegerField(default=0)),
                ('identity', models.FloatField(default=0)),
                ('coverage', models.FloatField(default=0)),
                ('classification', models.CharField(default='Desconocido', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_genes', to='analisis.analysisjob')),
            ],
        ),
    ]
