# Generated by Django 5.2.7 on 2025-11-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_detectedgene'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResistanceGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('CARD', 'CARD'), ('ResFinder', 'ResFinder')], max_length=20)),
                ('gene_name', models.CharField(max_length=100, unique=True)),
                ('sequence', models.TextField()),
                ('antibiotic_class', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
