# Generated by Django 5.2.7 on 2025-11-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_resistancegene'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='risk_level',
            field=models.CharField(choices=[('NONE', 'Sin riesgo'), ('LOW', 'Bajo'), ('MEDIUM', 'Moderado'), ('HIGH', 'Crítico')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='detectedgene',
            name='antibiotic_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detectedgene',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
